version: "3.8"

services:
  server:
    build: ./server # Points to the Dockerfile for the python aoo
    command: python app.py # Command to run the app
    ports:
      - "8000:8000" # Expose port 8000 (Fastapi's default)
    volumes:
      - ./server:/app # Mount the app for live updates

  client:
    build: ./client # Points to the Dockerfile for the react app
    command: yarn run start # Command to run the app
    ports:
      - "3000:3000" # (React's default)
    volumes:
      - ./client:/app # Mount the app for live updates
    depends_on:
      - server # Ensure the server starts first

